config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :resources
  # Defines the root path route ("/")
  # root "articles#index"

  resources :roadmaps, only: [:show]

  resources :checkpoints, only: %i[index show new create]
  get 'login/index', as: :login_index
  get 'checkpoints/:id/resource' => 'resources#index', as: :checkpoint_resource
  get 'challenges/:id' => 'challenge_personals#show', as: :challenge_personal
  get 'checkpoints/:id/challenges' => 'challenge_personals#index', as: :checkpoint_challenge_personal
  post 'checkpoints/:id/challenges' => 'challenge_personals#create', as: :checkpoint_challenge_personals
  get 'checkpoints/:id/challenges/new' => 'challenge_personals#new', as: :challenge_personal_new

  root 'roadmaps#show', defaults: { id: '1' }
  post 'challenges/:id/enroll' => 'challenge_personals#enroll_challenge', as: :enroll_challenge
  # root to:"login#index"
  resources :challenge_personals, only: %i[index show new]
end

app/models/challenge_personal.rb
class ChallengePersonal < ApplicationRecord
  belongs_to :checkpoint
  has_many :user_challenge_assigments, dependent: :destroy
end

app/controllers/challenge_personals_controller.rb
class ChallengePersonalsController < ApplicationController
  before_action :set_challenge_personal, only: %i[show enroll_challenge]
  before_action :set_checkpoint, only: %i[index]

  def index
    @list_challenge_personal = @checkpoint.challenge_personals
  end

  def show; end

  def new
    @challenge_personal = ChallengePersonal.new
    @checkpoint = Checkpoint.find(params[:id])
  end

  def create
    url = params[:challenge_personal][:url]
    url = 'https://' << url if !url.nil? && !url.start_with?('http')
    @challenge_personal = ChallengePersonal.new(name: params[:challenge_personal][:name],
                                                description: params[:challenge_personal][:description],
                                                url:, checkpoint_id: params[:id])

    if @challenge_personal.save
      redirect_to @challenge_personal
    else
      render :new, status: :unprocessable_entity
    end
  end

  def enroll_challenge
    if !@user_already_enrolled
      @user_challenge_assignment = UserChallengeAssigment.new(user_id: current_user.id,
                                                              challenge_personal_id: @challenge_personal.id)
      if @user_challenge_assignment.save
        flash[:notice] = 'Estás inscrito en el Desafío!'
        puts 'Estás inscrito en el Desafío!'
      else
        flash[:alert] = 'Error al inscribirse en el Desafío'
        puts 'Error al inscribirse en el Desafío'
      end
    else
      flash[:alert] = 'Ya estas inscrito en el Desafío'
      puts 'Ya estas inscrito en el Desafío'
    end
    redirect_to checkpoint_challenge_personal_path
  end

  private

  def set_challenge_personal
    @challenge_personal = ChallengePersonal.find(params[:id])
    @user_already_enrolled = UserChallengeAssigment.exists?(
      user_id: current_user.id,
      challenge_personal_id: @challenge_personal.id)
  end

  def set_checkpoint
    checkpoint_id = if params[:resource].present?
                      params[:resource][:checkpoint_id]
                    else
                      params[:id]
                    end

    @checkpoint = Checkpoint.find(checkpoint_id)
  end
end

app/helpers/challenge_personals_helper.rb
module ChallengePersonalsHelper
end

app/views/challenge_personals/_form.html.erb
<%= form_with model: [ @checkpoint, @challenge_personal ], 
    class: 'space-y-3 my-5 ',
    local: true do |form| %>
    <div>
      <%= form.label :name, 
        class: "pr-10" %>
      <%= form.text_field :name, 
        class: "bg-gray-50 border border-gray-300 text-gray-900 
          text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 
          block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 
          dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500
          dark:focus:border-blue-500" %>
    </div>
    <div>
      <%= form.label :description, 
        class: "pr-10" %>
      <%= form.text_area :description, 
        class: "bg-gray-50 border border-gray-300 text-gray-900 
          text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 
          block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 
          dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500
          dark:focus:border-blue-500" %>
    </div>


    <div>
      <%= form.label :url, 
        class: "pr-10" %>
      <%= form.text_field :url, 
        class: "bg-gray-50 border border-gray-300 text-gray-900 
          text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 
          block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 
          dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500
          dark:focus:border-blue-500" %>
    </div>
    
    <!--<div>
      <%= form.label :checkpoint_id, 
        class: "pr-10" %>
      <%= form.select :checkpoint_id, 
        :class => "mt-1 block w-full rounded-md border-gray-300 py-2 pl-3 pr-10 text-base focus:border-indigo-500 focus:outline-none focus:ring-indigo-500 sm:text-sm" %>
    </div>-->
        <%= form.submit "Guardar desafío personal",
        :class => "inline-flex items-center rounded border border-transparent bg-indigo-600
         px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 
         focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
<% end %>

app/views/challenge_personals/_list_of_challenge_personals.html.erb
<% if @list_challenge_personal %>
  <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg | my-5">
    <table class="table-auto | min-w-full divide-y divide-gray-300">
      <thead class="bg-gray-50">
        <tr class="text-left">
          <th class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">id</th>
          <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Nombre</th>
        </tr>
      </thead>
      <tbody>
        <% @list_challenge_personal.each do |personal_challenge| %>
          <tr>
            <td class="whitespace-nowrap py-2 pl-4 pr-3 text-sm font-medium text-gray-600 sm:pl-6 | hover:text-black"><%= personal_challenge.id%></td>
            <td class="whitespace-nowrap px-3 py-2 text-sm text-gray-500">
              <%= link_to personal_challenge.name, challenge_personal_path(personal_challenge),
                class: "inline-flex items-center rounded border border-gray-300 bg-white px-2.5 py-1.5 text-xs font-medium text-gray-700 shadow-sm hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/challenge_personals/index.html.erb
<div class="my-5">
  <h1 class="text-3xl uppercase font-bold | border-b border-gray-200 pb-5">Desafios personales</h1>
  <%=link_to 'Crear desafío personal', 
    challenge_personal_new_path(@checkpoint),
    class: "relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 mt-5" %>
  <%#= render "form", resources: @challenge_personal %>
  <%= render "list_of_challenge_personals", resources: @challenge_personal %>
</div>

app/views/challenge_personals/new.html.erb
<h1 class="mt-10 | text-3xl uppercase font-bold">Agregar nuevo desafío personal</h1>

<%= render "form", resources: @challenge_personal, locals: { checkpoint: @checkpoint } %>

app/views/challenge_personals/show.html.erb
<!--
<h2>Desafio personal</h2>
<hr>
<p><%= @challenge_personal.id %></p>
<p><%= @challenge_personal.name %></p>
<p><%= @challenge_personal.description %></p>
<p><%= @challenge_personal.url %></p> 

<% unless @user_already_enrolled %>
 <%= button_to "Inscribirme", enroll_challenge_path(id: @challenge_personal.id), method: :post %>
<% end %>
-->

<div class="border-b border-gray-200 pb-5 sm:flex sm:items-center sm:justify-between">
  <h1 class="text-3xl uppercase mt-10 font-medium leading-6 text-gray-900">Desafío Personal: <%= @challenge_personal.name%></h1>
  <div class="mt-3 sm:mt-0 sm:ml-4">
    <button type="button" class="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" onclick="javascript: history.back()">Volver</button>
  </div>
</div>

<dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-1 lg:grid-cols-1">
    <div class="relative overflow-hidden rounded-lg bg-white px-4 pt-5 pb-12 shadow">
      <dt>
        <div class="absolute rounded-md bg-indigo-500 p-3">
          <!-- Heroicon -->
          <svg  class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6z" />
          </svg>

        </div>
        <p class="ml-16 truncate text-sm font-medium text-gray-500"><%= @challenge_personal.name %></p>
      </dt>
      <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
        <p class="text-2xl font-semibold text-gray-900"><%= @challenge_personal.description %></p>
        <p class="ml-2 flex items-baseline text-sm font-semibold text-green-600">
          ID: <%= @challenge_personal.id %>
        </p>
        <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
          <div class="text-sm">
            <% if @user_already_enrolled %>
              <p target=_blank class="font-medium text-indigo-600 hover:text-indigo-500" > Estás Inscrito </p>
            <% else %>
              <p target=_blank class="font-medium text-indigo-600 hover:text-indigo-500" ><%= button_to "Inscribirme", enroll_challenge_path(id: @challenge_personal.id), method: :post, class: "inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %> </p>
            <% end %>
          </div>
        </div>
      </dd>
    </div>
</dl>