config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :resources
  # Defines the root path route ("/")
  # root "articles#index"

  resources :roadmaps, only: [:show]

  resources :checkpoints, only: %i[index show new create]
  get 'login/index', as: :login_index
  get 'checkpoints/:id/resource' => 'resources#index', as: :checkpoint_resource
  get 'challenges/:id' => 'challenge_personals#show', as: :challenge_personal
  get 'checkpoints/:id/challenges' => 'challenge_personals#index', as: :checkpoint_challenge_personal
  post 'checkpoints/:id/challenges' => 'challenge_personals#create', as: :checkpoint_challenge_personals
  get 'checkpoints/:id/challenges/new' => 'challenge_personals#new', as: :challenge_personal_new

  root 'roadmaps#show', defaults: { id: '1' }
  post 'challenges/:id/enroll' => 'challenge_personals#enroll_challenge', as: :enroll_challenge
  # root to:"login#index"
  resources :challenge_personals, only: %i[index show new]
end

app/models/Roadmap.rb
class Roadmap < ApplicationRecord
  has_many :roadmaps_users, dependent: :destroy
  has_many :users, through: :roadmaps_users

  has_many :mentors_roadmaps, dependent: :destroy
  has_many :mentors, through: :mentors_roadmaps

  has_many :checkpoint_roadmaps
  has_many :checkpoints, through: :checkpoint_roadmaps

  validates :name, presence: true
  validates :description, presence: true
end

app/models/roadmap.rb
class Roadmap < ApplicationRecord
  has_many :roadmaps_users, dependent: :destroy
  has_many :users, through: :roadmaps_users

  has_many :checkpoint_roadmaps
  has_many :checkpoints, through: :checkpoint_roadmaps

  validates :name, presence: true
  validates :description, presence: true
end

app/models/roadmap_.rb
class Roadmap < ApplicationRecord
  has_many :roadmaps_users, dependent: :destroy
  has_many :users, through: :roadmaps_users

  has_many :mentors_roadmaps, dependent: :destroy
  has_many :mentors, through: :mentors_roadmaps

  has_many :checkpoint_roadmaps
  has_many :checkpoints, through: :checkpoint_roadmaps

  validates :name, presence: true
  validates :description, presence: true
end

app/controllers/roadmaps_controller.rb
class RoadmapsController < ApplicationController
  include Authenticator

  def show
    @roadmap = Roadmap.find(params[:id])
  end
end

app/helpers/roadmaps_helper.rb
module RoadmapsHelper
end

app/views/roadmaps/index.html.erb
<h1>Roadmaps#index</h1>
<% @roadmaps.each do |road| %>
<p><%= road.name %></p>
<p><%= road.description %></p>
<p><%= link_to 'Ver más', roadmap_path(road) %></p>
<% end %>

app/views/roadmaps/show.html.erb
<h1 class="mt-10 | text-3xl uppercase font-bold"><%= @roadmap.name %></h1>
<h1 class="mt-2 | text-lg">Sendero</h1>
<p><%= @roadmap.description %></p>

<h2 class="mt-10 | text-2xl uppercase font-bold">Hitos</h2>
<%=link_to 'Crear hito', 
    new_checkpoint_path,
    class: "relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500 mt-5" %>

<div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg | my-5">
  <table class="table-auto | min-w-full divide-y divide-gray-300">
  <thead class="bg-gray-50">
      <tr class="text-left">
        <th class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">Nombre</th>
        <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Descripción</th>
        <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Acciones</th>
      </tr>
    </thead>
    <tbody class="bg-white">
    <% @roadmap.checkpoints.each do |checkpoint| %>
      <tr>
        <td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-600 sm:pl-6 | hover:text-black">
          <%= link_to checkpoint.name, checkpoint_path(checkpoint) %>
        </td>
        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500"><%= checkpoint.description %></td>
        <td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500">
          <span class="isolate inline-flex rounded-md shadow-sm">
            <%= link_to checkpoint_resource_path(checkpoint), class: "relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500" do %>
              <!-- https://heroicons.com -->
              <svg class="-ml-1 mr-2 h-5 w-5 text-red-900 hover:text-red-900" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                <path fill-rule="evenodd" d="M10 1c-1.716 0-3.408.106-5.07.31C3.806 1.45 3 2.414 3 3.517V18.25a.75.75 0 001.075.676L10 16.082l5.925 2.844A.75.75 0 0017 18.25V3.517c0-1.103-.806-2.068-1.93-2.207A41.403 41.403 0 0010 1z" clip-rule="evenodd" />
              </svg> 
              Recursos
            <% end %>
          </span>
          
          <span class="isolate inline-flex rounded-md shadow-sm">
            <%= link_to checkpoint_challenge_personal_path(checkpoint), class: "relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500" do %>
              <!-- https://heroicons.com -->
              <svg class="-ml-1 mr-2 h-5 w-5 text-red-900 hover:text-red-900" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
              <path stroke-linecap="round" stroke-linejoin="round" d="M4.26 10.147a60.436 60.436 0 00-.491 6.347A48.627 48.627 0 0112 20.904a48.627 48.627 0 018.232-4.41 60.46 60.46 0 00-.491-6.347m-15.482 0a50.57 50.57 0 00-2.658-.813A59.905 59.905 0 0112 3.493a59.902 59.902 0 0110.399 5.84c-.896.248-1.783.52-2.658.814m-15.482 0A50.697 50.697 0 0112 13.489a50.702 50.702 0 017.74-3.342M6.75 15a.75.75 0 100-1.5.75.75 0 000 1.5zm0 0v-3.675A55.378 55.378 0 0112 8.443m-7.007 11.55A5.981 5.981 0 006.75 15.75v-1.5" />
            </svg>
              Desafios
            <% end %>
          </span>

        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>