config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :resources
  # Defines the root path route ("/")
  # root "articles#index"

  resources :roadmaps, only: [:show]

  resources :checkpoints, only: %i[index show new create]
  get 'login/index', as: :login_index
  get 'checkpoints/:id/resource' => 'resources#index', as: :checkpoint_resource
  get 'challenges/:id' => 'challenge_personals#show', as: :challenge_personal
  get 'checkpoints/:id/challenges' => 'challenge_personals#index', as: :checkpoint_challenge_personal
  post 'checkpoints/:id/challenges' => 'challenge_personals#create', as: :checkpoint_challenge_personals
  get 'checkpoints/:id/challenges/new' => 'challenge_personals#new', as: :challenge_personal_new

  root 'roadmaps#show', defaults: { id: '1' }
  post 'challenges/:id/enroll' => 'challenge_personals#enroll_challenge', as: :enroll_challenge
  # root to:"login#index"
  resources :challenge_personals, only: %i[index show new]
end

app/models/Roadmap.rb
class Roadmap < ApplicationRecord
  has_many :roadmaps_users, dependent: :destroy
  has_many :users, through: :roadmaps_users

  has_many :mentors_roadmaps, dependent: :destroy
  has_many :mentors, through: :mentors_roadmaps

  has_many :checkpoint_roadmaps
  has_many :checkpoints, through: :checkpoint_roadmaps

  validates :name, presence: true
  validates :description, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/challenge_personal.rb
class ChallengePersonal < ApplicationRecord
  belongs_to :checkpoint
  has_many :user_challenge_assigments, dependent: :destroy
end

app/models/checkpoint.rb
class Checkpoint < ApplicationRecord
  has_many :challenge_personals, dependent: :destroy

  has_many :checkpoint_resources, dependent: :destroy
  has_many :resources, through: :checkpoint_resources, dependent: :destroy

  has_many :checkpoint_roadmaps
  has_many :roadmaps, through: :checkpoint_roadmaps

  validates :name, presence: true
  validates :description, presence: true
end

app/models/checkpoint_resource.rb
class CheckpointResource < ApplicationRecord
  belongs_to :checkpoint
  belongs_to :resource
end

app/models/checkpoint_roadmap.rb
class CheckpointRoadmap < ApplicationRecord
  belongs_to :checkpoint
  belongs_to :roadmap
end

app/models/path.rb
class Path < ApplicationRecord
  has_and_belongs_to_many :checkpoints

  has_many :user_paths, dependent: :destroy
  has_many :users, through: :user_path,
  has_many :user_path_users, through: :user_path, class_name: "User",
                                     foreign_key: "user_id"
  has_many :user_mentor_paths, dependent: :destroy
  has_many :user_mentor_paths_users, through: :user_mentor_paths, class_name: "User",
                                     foreign_key: "user_id"
  validates :name, presence: true
  validates :description, presence: true
end

app/models/resource.rb
class Resource < ApplicationRecord
  has_many :checkpoint_resources, dependent: :destroy
  has_many :checkpoints, through: :checkpoint_resources, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true
  validates :url, presence: true
end

app/models/roadmap.rb
class Roadmap < ApplicationRecord
  has_many :roadmaps_users, dependent: :destroy
  has_many :users, through: :roadmaps_users

  has_many :checkpoint_roadmaps
  has_many :checkpoints, through: :checkpoint_roadmaps

  validates :name, presence: true
  validates :description, presence: true
end

app/models/roadmap_.rb
class Roadmap < ApplicationRecord
  has_many :roadmaps_users, dependent: :destroy
  has_many :users, through: :roadmaps_users

  has_many :mentors_roadmaps, dependent: :destroy
  has_many :mentors, through: :mentors_roadmaps

  has_many :checkpoint_roadmaps
  has_many :checkpoints, through: :checkpoint_roadmaps

  validates :name, presence: true
  validates :description, presence: true
end

app/models/roadmap_user.rb
class RoadmapUser < ApplicationRecord
  belongs_to :user
  belongs_to :roadmap
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :lockable
  has_many :UserChallengeAssignment, dependent: :destroy
  has_many :resources, through: :user_read_resources, dependent: :destroy

  has_many :roadmap_users, dependent: :destroy
  has_many :roadmaps, through: :roadmap_users
end

app/models/user_challenge_assigment.rb
class UserChallengeAssigment < ApplicationRecord
  belongs_to :user
  belongs_to :challenge_personal
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    return redirect_to new_user_session_path unless user_signed_in?

    redirect_to root_path
  end
end

app/controllers/roadmaps_controller.rb
class RoadmapsController < ApplicationController
  include Authenticator

  def show
    @roadmap = Roadmap.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/checkpoints_helper.rb
module CheckpointsHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/resource_helper.rb
module ResourceHelper
end

app/helpers/roadmaps_helper.rb
module RoadmapsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Paraffin</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://cdn.tailwindcss.com"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    </head>
    
    <body>
    <div class="md:flex md:items-center md:justify-between bg-black px-20 py-3">
      <div class="min-w-0 flex-1">
        <h2 class="text-2xl font-bold leading-7 text-white sm:truncate sm:text-3xl sm:tracking-tight"><%= link_to_unless_current "Paraffin", 
        root_path %><span class='text-5xl text-red-700'>.</span>  🦙</h2>
      </div>
      <div class="mt-4 flex md:mt-0 md:ml-4">
        <%= link_to_unless_current "Home", 
            login_index_path, 
            :class => "text-white px-4 py-2" %>
        <% if current_user %>
          <%= link_to current_user.full_name, 
              edit_user_registration_path,
              :class => "text-white px-4 py-2" %>
          <%= button_to "Salir", 
            destroy_user_session_path, 
            method: :delete, 
            data: { turbo: false },
            :class => "inline-flex items-center rounded-md border border-transparent bg-gray-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-800" 
            %>
        <% else %>
          <%= link_to_unless_current "Registrarse", 
              new_user_registration_path,
              :class => "text-white px-4 py-2" %>
          <%= link_to_unless_current "Ingresar", 
              new_user_session_path,
              :class => "text-white px-4 py-2" %>
        <% end %>
      </div>
    </div>
    <div class="mx-20">  
      <%= yield %>
    </div>
  </body>
</html>

app/views/resources/_form.html.erb
<%= form_with model: Resource.new, 
    class: 'space-y-3 my-5 ', 
    local: true do |form| %>
    <div>
      <%= form.label :name, 
        class: "pr-10" %>
      <%= form.text_field :name, 
        class: "bg-gray-50 border border-gray-300 text-gray-900 
          text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 
          block w-full p-2.5 dark:bg-gray-700 dark:border-gray-600 
          dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500
          dark:focus:border-blue-500" %>
    </div>
    <div>
      <%= form.label :description, 
        class: "pr-10" %>
      <%= form.text_field :description, 
        class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm 
          rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full 
          p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 
          dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
    <div>
      <%= form.label :url, 
          class: "pr-10" %>
      <%= form.text_field :url, 
          class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg
             focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700
              dark:border-gray-600 dark:placeholder-gray-400 dark:text-white 
              dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    </div>
    <%= form.hidden_field :checkpoint_id,
        value: @checkpoint.id,
        class: "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg 
          focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 
          dark:border-gray-600 dark:placeholder-gray-400 dark:text-white 
          dark:focus:ring-blue-500 dark:focus:border-blue-500" %>
    <div>
      <%= 
        form.submit 'Guardar', 
        :class => "inline-flex items-center rounded border border-transparent bg-indigo-600
         px-2.5 py-1.5 text-xs font-medium text-white shadow-sm hover:bg-indigo-700 
         focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" %>
    </div>
<% end %>

app/views/resources/_list_of_resources.html.erb
<!-- Show list of resources -->
<% if @list_resources %>
  <div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 md:rounded-lg | my-5">
    <table class="table-auto | min-w-full divide-y divide-gray-300">
      <thead class="bg-gray-50">
        <tr class="text-left">
          <th class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6">ID</th>
          <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Nombre</th>
          <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Descripción</th>
          <th class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900">Acciones</th>
        </tr>
      </thead>
      <tbody>
      <% @list_resources.each do |resource| %>
        <tr>
          <td class="whitespace-nowrap py-2 pl-4 pr-3 text-sm font-medium text-gray-600 sm:pl-6 | hover:text-black"><%= link_to resource.id, resource %></td>
          <td class="whitespace-nowrap px-3 py-2 text-sm text-gray-500"><%= resource.name %></td>
          <td class="whitespace-nowrap px-3 py-2 text-sm text-gray-500"><%= resource.description %></td>
          <td class="whitespace-nowrap px-3 py-2 text-sm text-gray-500">
            <span class="isolate inline-flex rounded-md shadow-sm">
              <%= link_to resource_path(resource), 
                  class: "relative inline-flex items-center rounded-md border border-gray-300 bg-white px-4 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50 focus:z-10 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500" do %>
                <!-- https://heroicons.com -->
                <svg class="-ml-1 mr-2 h-5 w-5 text-red-900 hover:text-red-900" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                  <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" />
                  <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6z" />
                </svg>
                Ver
              <% end %>
            </span>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/resources/index.html.erb
<div class="my-5">
  <nav class="hidden sm:flex" aria-label="Breadcrumb">
    <ol role="list" class="flex items-center space-x-4">
      <li>
        <div class="flex">
          <%= link_to 'Hitos', 
            checkpoints_path(), 
            class: "text-sm font-medium text-gray-500 hover:text-gray-700" %>
        </div>
      </li>
      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
          <%= link_to @checkpoint.name, 
            checkpoint_path, 
            class: "ml-4 text-sm font-medium text-gray-500 hover:text-gray-700" %>
        </div>
      </li>
      <li>
        <div class="flex items-center">
          <!-- Heroicon name: mini/chevron-right -->
          <svg class="h-5 w-5 flex-shrink-0 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
            <path fill-rule="evenodd" d="M7.21 14.77a.75.75 0 01.02-1.06L11.168 10 7.23 6.29a.75.75 0 111.04-1.08l4.5 4.25a.75.75 0 010 1.08l-4.5 4.25a.75.75 0 01-1.06-.02z" clip-rule="evenodd" />
          </svg>
          <span class="ml-4 text-sm font-medium text-gray-500 hover:text-gray-700">
          Recursos
          </span>
        </div>
      </li>
    </ol>
  </nav>
</div>

<h1 class="text-3xl uppercase font-bold | border-b border-gray-200 pb-5">Recursos</h1>

<% flash.each do |key, value| %>
  <% if key == "success" %>
    <div class="bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <h3 class="text-lg font-medium leading-6 text-green-900">
          Registro exitoso
        </h3>
        <div class="mt-2 max-w-xl text-sm text-gray-500">
          <p><%= value %></p>
        </div>
      </div>
    </div>
  <% end %>
  <% if key == "error" %>
    <div class="bg-white shadow sm:rounded-lg">
      <div class="px-4 py-5 sm:p-6">
        <h3 class="text-lg font-medium leading-6 text-red-900">
          Oops! algo falló
        </h3>
        <div class="mt-2 max-w-xl text-sm text-gray-500">
          <p><%= value %></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>


<%= render "form", resources: @resources %>
<h2 class="mt-1 | text-lg">
  Listado de todos los recursos asociados al hito 
  <%= link_to @checkpoint.name, checkpoint_path(), 
  class: "inline-flex items-center rounded border 
    border-gray-300 bg-white px-2.5 py-1.5 text-xs 
    font-medium text-gray-700 shadow-sm hover:bg-gray-50 
    focus:outline-none focus:ring-2 focus:ring-indigo-500 
    focus:ring-offset-2" %>.
</h2>
<%= render "list_of_resources", resources: @resources %>

app/views/resources/show.html.erb
<div class="border-b border-gray-200 pb-5 sm:flex sm:items-center sm:justify-between">
  <h1 class="text-3xl uppercase mt-10 font-medium leading-6 text-gray-900">Detalle del recurso</h1>
  <div class="mt-3 sm:mt-0 sm:ml-4">
    <button type="button" class="inline-flex items-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2" onclick="javascript: history.back()">Volver</button>
  </div>
</div>

<dl class="mt-5 grid grid-cols-1 gap-5 sm:grid-cols-1 lg:grid-cols-1">
    <div class="relative overflow-hidden rounded-lg bg-white px-4 pt-5 pb-12 shadow">
      <dt>
        <div class="absolute rounded-md bg-indigo-500 p-3">
          <!-- Heroicon -->
          <svg  class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
            <path stroke-linecap="round" stroke-linejoin="round" d="M9.568 3H5.25A2.25 2.25 0 003 5.25v4.318c0 .597.237 1.17.659 1.591l9.581 9.581c.699.699 1.78.872 2.607.33a18.095 18.095 0 005.223-5.223c.542-.827.369-1.908-.33-2.607L11.16 3.66A2.25 2.25 0 009.568 3z" />
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 6h.008v.008H6V6z" />
          </svg>

        </div>
        <p class="ml-16 truncate text-sm font-medium text-gray-500"><%= @resource.name %></p>
      </dt>
      <dd class="ml-16 flex items-baseline pb-6 sm:pb-7">
        <p class="text-2xl font-semibold text-gray-900"><%= @resource.description %></p>
        <p class="ml-2 flex items-baseline text-sm font-semibold text-green-600">
          ID: <%= @resource.id %>
        </p>
        <div class="absolute inset-x-0 bottom-0 bg-gray-50 px-4 py-4 sm:px-6">
          <div class="text-sm">
            <a href="<%= @resource.url %>"target=_blank class="font-medium text-indigo-600 hover:text-indigo-500"> Acceder al recurso</a>
          </div>
        </div>
      </dd>
    </div>
</dl>